"""LaTeX preview functionality"""
import subprocess
import os
from pathlib import Path


class LaTeXPreview:
    """Generate preview of LaTeX content"""

    def __init__(self, output_dir: str = "output"):
        self.output_dir = output_dir
        Path(output_dir).mkdir(exist_ok=True)

    def generate_pdf(self, latex_content: str, output_name: str = "preview") -> str:
        """
        Compile LaTeX to PDF

        Args:
            latex_content: LaTeX source code
            output_name: Name for the output file (without extension)

        Returns:
            Path to the generated PDF file
        """
        # Save LaTeX to temporary file
        tex_file = os.path.join(self.output_dir, f"{output_name}.tex")
        with open(tex_file, 'w', encoding='utf-8') as f:
            f.write(latex_content)

        # Compile LaTeX to PDF using pdflatex
        try:
            # Run pdflatex (suppress output)
            result = subprocess.run(
                ['pdflatex', '-interaction=nonstopmode', '-output-directory', self.output_dir, tex_file],
                capture_output=True,
                text=True,
                timeout=30
            )

            pdf_file = os.path.join(self.output_dir, f"{output_name}.pdf")

            if os.path.exists(pdf_file):
                # Clean up auxiliary files
                self._cleanup_aux_files(output_name)
                return pdf_file
            else:
                raise Exception(f"PDF generation failed. LaTeX output:\n{result.stdout}\n{result.stderr}")

        except FileNotFoundError:
            # pdflatex not installed
            print("Warning: pdflatex not found. PDF preview not available.")
            print("To enable PDF preview, install LaTeX: sudo apt-get install texlive-latex-base")
            return tex_file
        except subprocess.TimeoutExpired:
            raise Exception("LaTeX compilation timed out")
        except Exception as e:
            raise Exception(f"Failed to generate PDF: {str(e)}")

    def _cleanup_aux_files(self, output_name: str):
        """Remove auxiliary files generated by LaTeX"""
        extensions = ['.aux', '.log', '.out']
        for ext in extensions:
            aux_file = os.path.join(self.output_dir, f"{output_name}{ext}")
            if os.path.exists(aux_file):
                try:
                    os.remove(aux_file)
                except:
                    pass

    def save_latex(self, latex_content: str, output_name: str = "output") -> str:
        """
        Save LaTeX content to file

        Args:
            latex_content: LaTeX source code
            output_name: Name for the output file (without extension)

        Returns:
            Path to the saved .tex file
        """
        tex_file = os.path.join(self.output_dir, f"{output_name}.tex")
        with open(tex_file, 'w', encoding='utf-8') as f:
            f.write(latex_content)

        return tex_file
